### ISSUE TITLE
Configure keycloak to work with jwt-to-rbac

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-tasks#13]
# Tasks:
- [ ] The jwt-to-rbac requires an extra claim:

The claim should be added to `otomi` client at `openid` scope

The claim configuration is:
```
{"name":"FederatedClaims (jwt-to-rbac)","protocol":"openid-connect","protocolMapper":"oidc-hardcoded-claim-mapper","consentRequired":false,"config":{"claim.value":"{\"connector_id\": \"local\", \"user_id\": \"not_applicable\"}","userinfo.token.claim":"true","id.token.claim":"true","access.token.claim":"true","claim.name":"federated_claims","jsonType.label":"JSON"}}
```

The claim `config` is provided by env variables: `IDP_JWT_TO_RBAC_CLAIM_NAME` and `IDP_JWT_TO_RBAC_CLAIM_VALUE`

# References:
https://github.com/redkubes/otomi-core/issues/215

**Comment by j-zimnowoda** [comment]
@rawc0der maybe this task would be a good match for you?

**Comment by Morriz** [comment]
@j-zimnowoda I know you went through a lot of investigation and did a lot of work, so can I ask you how much work is left here? This would really be beneficial to have asap.

Use case: kubeapps / operator installer

**Comment by Morriz** [comment]
@rawc0der it would be awesome if you can set this up in keycloak after delivery of conftest PR

**Comment by Morriz** [comment]
closing in favor of choosing standards choice done here: https://github.com/redkubes/otomi-core/issues/207
