### ISSUE TITLE
Create `admin` user in keycloak

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-tasks#65]
**Is your feature request related to a problem? Please describe.**

After installing otomi I would like to immediately be able to login to otomi console.

**Describe the solution you'd like**
The keycloak job creates the `admin` user that has the same password as keycloak admin user.
The `admin` user should belong to `otomi-admin` group that is created by the same keycloak job.

A user should be created only if `otomi.hasExternalIDP` is set to `false`

**Comment by Morriz** [comment]
released version `0.2.22` and added it to otomi-core@master
